# .github/workflows/firebase-deploy.yml (example)
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main # Or your deployment branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults: # Add this if your package.json is in a subdirectory
      run:
        working-directory: ./my-app # Adjust if your app is in a different subfolder
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your project's Node.js version

      - name: Install Dependencies
        run: npm ci # Installs dependencies from package-lock.json

      - name: Build Project
        run: npm run build
        env: # Ensure your build script has access to necessary env vars
          REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}
          # Add other environment variables needed for the build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HACCP_HERB_X_TEA }}' # Or your Firebase token secret
          channelId: live
          projectId: haccp-herb-x-tea
          target: your-hosting-target # if you use multiple sites, otherwise remove
          entryPoint: ./my-app # Path to your app's root
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
